
package pdf;
import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfCopy;
import com.lowagie.text.pdf.*;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.Document;

import utils.Alerthelper;


import java.io.FileOutputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.io.File;
import java.util.List;
import java.util.Map;
import java.util.Date;
import java.util.HashMap;
import java.text.DateFormat;
import java.nio.file.*;
import java.util.Arrays;

public class GeneratePdf {
    private static final Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 16);
    private static final Font regularFont = FontFactory.getFont(FontFactory.HELVETICA, 9);
    private static final Font BODY_FONT = new Font(Font.HELVETICA, 11,Font.NORMAL);
    private static final Font sub_title_font = new Font(Font.HELVETICA,12,Font.BOLD);
    private static final Font footerFont = FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 9);
    private static final Font table_header_font = new Font(Font.HELVETICA,11,Font.BOLD);

    private static final Date current_date = new Date();

    public static void mergePdf(String folderPath,String outputpath){
        File folder = new File(folderPath);
        File[] pdffiles = folder.listFiles((dir,name) -> name.toLowerCase().endsWith(".pdf"));
        if (pdffiles == null || pdffiles.length == 0){
            System.out.println("No pdf files found");
            return;
        }
        Arrays.sort(pdffiles);

        try {
            Document document = new Document();
            PdfCopy copy = new PdfCopy(document,new FileOutputStream(outputpath));
            document.open();

            for(File file : pdffiles){
                System.out.println("Path found "+file.getAbsolutePath().toString());
                PdfReader reader = new PdfReader(file.getAbsolutePath());
                int n =  reader.getNumberOfPages();
                for (int i = 1; i<= n; i++){
                    copy.addPage(copy.getImportedPage(reader,i));
                }
                reader.close();
            }
            document.close();
            System.out.println("Pdf merged: "+outputpath);
        } catch (Exception e){
            e.printStackTrace();
        }
    }


    public static void addHeader(Document document,PdfWriter writer,String school_name,String contactinfo,String sub_title,String logo_path)throws Exception{
        PdfPTable table = new PdfPTable(3);
        table.setWidths(new float[]{1,4,1});
        table.setWidthPercentage(100);

        Image logo = Image.getInstance(logo_path);
        logo.scaleToFit(50,50);
        PdfPCell logo_cell = new PdfPCell(logo);
        logo_cell.setBorder(Rectangle.NO_BORDER);

        logo_cell.setHorizontalAlignment(Element.ALIGN_LEFT);
        table.addCell(logo_cell);

        PdfPCell title_cell = new PdfPCell();
        title_cell.setBorder(Rectangle.NO_BORDER);
        title_cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        title_cell.addElement(new Paragraph(school_name,new Font(Font.HELVETICA,14,Font.BOLD)));
        title_cell.addElement(new Paragraph(contactinfo,new Font(Font.HELVETICA,9)));
        title_cell.addElement(new Paragraph(sub_title,new Font(Font.HELVETICA,10,Font.BOLD)));
        table.addCell(title_cell);

        PdfPCell empty = new PdfPCell();
        empty.setBorder(Rectangle.NO_BORDER);
        table.addCell(empty);

        document.add(table);
        // doc.add(new LineSeparator());
    }

    public static void addFooter(PdfWriter writer){
        PdfContentByte cb = writer.getDirectContent();
        cb.beginText();
        try {
            BaseFont bf = BaseFont.createFont();
            cb.setFontAndSize(bf,9);

            cb.showTextAligned(PdfContentByte.ALIGN_RIGHT,"Generated by ShuleBase",550,30,0);
        } catch (Exception e){
            e.printStackTrace();
        }
        cb.endText();
    }
    

    private static void addGeneratedNote(Document document) throws DocumentException {
        Paragraph footer = new Paragraph("This is a ShuleBase generated file", footerFont);
        footer.setAlignment(Element.ALIGN_CENTER);
        document.add(footer);
    }

 
    public static void generateFeeReceipt(String output_path,String reg_no,String name,String grade,String stream,String term,String date,String time,double amount,double balance,String mode_of_payment)throws Exception {
        Document document = new Document(PageSize.A4,40,40,90,50);
        // document.setBackgroundColor(BaseColor.BLUE);
        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(output_path));
        writer.setFullCompression();
        writer.setPdfVersion(PdfWriter.PDF_VERSION_1_4);
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","FEE RECEIPT","resources/images/logo.png");
        Paragraph details = new Paragraph(String.format("Reg No: %s Name: %s    Grade: %s   Stream: %s",reg_no,name,grade,stream),BODY_FONT);
        details.setSpacingBefore(5);
        document.add(details);
        document.add(new Paragraph(" "));

        PdfPTable info_table = new PdfPTable(4);
        info_table.setWidths(new float[]{2,3,2,3});
        info_table.setWidthPercentage(80);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        info_table.addCell(new PdfPCell(new Phrase("Term",header_font)));
        info_table.addCell(new PdfPCell(new Phrase("Date",header_font)));
        info_table.addCell(new PdfPCell(new Phrase("Time",header_font)));
        info_table.addCell(new PdfPCell(new Phrase("Pay Mode",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);

        info_table.addCell(new PdfPCell(new Phrase(term,row_font)));
        info_table.addCell(new PdfPCell(new Phrase(date,row_font)));
        info_table.addCell(new PdfPCell(new Phrase(time,row_font)));
        info_table.addCell(new PdfPCell(new Phrase(mode_of_payment,row_font)));

    

        
        document.add(info_table);
        document.add(new Paragraph(" "));

        PdfPTable table = new PdfPTable(2);
        table.setWidths(new float[]{3 , 2});
        table.setWidthPercentage(80);
        addTableHeader(table);

        double total = 0;
        Map<String,Double> categories = Map.of(
            "Food",0.3,
            "Games",0.1,
            "Tuition",0.4,
            "PTA",0.2
        );
        for(Map.Entry<String,Double> entry : categories.entrySet()){
            String category = entry.getKey();
            double percent = entry.getValue();
            double portion = amount * percent;
            addTableRow(table,category,portion,false);
            total += portion;
        }
        addTableRow(table,"Total",total,true);
        document.add(new Paragraph(" "));
        addTableRow(table,"Balance",balance,true);
        document.add(table);
        addFooter(writer);
        document.close();
    }
    private static void addTableHeader(PdfPTable table){
        Font headerfont = new Font(Font.HELVETICA,11,Font.BOLD);
        table.addCell(new PdfPCell(new Phrase("Category",headerfont)));
        table.addCell(new PdfPCell(new Phrase("Amount",headerfont)));
    }
    // private static void addTableRow(PdfPTable table,String item,double amount){
    //     addTableRow(table,item,amount,false);
    // }
    private static void addTableRow(PdfPTable table,String item,double amount,boolean isBold){
        Font rowfont = new Font(Font.HELVETICA,11,isBold ? Font.BOLD : Font.NORMAL);
        table.addCell(new PdfPCell(new Phrase(item,rowfont)));
        table.addCell(new PdfPCell(new Phrase(String.format("%.2f",amount),rowfont)));
    }
    

    public static void generateLeaveReceipt(String reg_no,String grade,String stream,String name,String reason,String other_reason,double balance,String term,String date, String time, String outputPath)throws Exception {
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            document.open();
            addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","LEAVE RECEIPT","resources/images/logo.png");
            addFooter(writer);

            document.add(new Paragraph(" "));

            document.add(new Paragraph(" "));

            PdfPTable header_table = new PdfPTable(4);
            header_table.setWidths(new float[]{2,2,2,2});
            header_table.setWidthPercentage(100);
            header_table.addCell(new PdfPCell(new Phrase("Reg No",table_header_font)));
            header_table.addCell(new PdfPCell(new Phrase("Name",table_header_font)));
            header_table.addCell(new PdfPCell(new Phrase("Grade",table_header_font)));
            header_table.addCell(new PdfPCell(new Phrase("Stream",table_header_font)));

            header_table.addCell(new PdfPCell(new Phrase(reg_no,regularFont)));
            header_table.addCell(new PdfPCell(new Phrase(name,regularFont)));
            header_table.addCell(new PdfPCell(new Phrase(grade,regularFont)));
            header_table.addCell(new PdfPCell(new Phrase(stream,regularFont)));
            document.add(header_table);

            document.add(new Paragraph(" "));
            
            PdfPTable header2_table = new PdfPTable(3);
            header2_table.setWidths(new float[]{2,2,2});
            header2_table.setWidthPercentage(100);
            header2_table.addCell(new PdfPCell(new Phrase("Term",table_header_font)));
            header2_table.addCell(new PdfPCell(new Phrase("Date",table_header_font)));
            header2_table.addCell(new PdfPCell(new Phrase("Time",table_header_font)));

            header2_table.addCell(new PdfPCell(new Phrase(term,regularFont)));
            header2_table.addCell(new PdfPCell(new Phrase(date,regularFont)));
            header2_table.addCell(new PdfPCell(new Phrase(time,regularFont)));

            document.add(header2_table);

            Paragraph stmt = new Paragraph("This is a confirmation statement for the student \n with above details that \n has been granted permission to be out of school due to:",footerFont);
            stmt.setAlignment(Element.ALIGN_CENTER);
            document.add(stmt);
            

            document.add(new Paragraph(" "));

            PdfPTable statement_table = new PdfPTable(2);
            statement_table.setWidths(new float[]{2,2});
            statement_table.setWidthPercentage(100);
            if(reason.equals("School Fees")){
                statement_table.addCell(new PdfPCell(new Phrase("Reason",table_header_font)));
                statement_table.addCell(new PdfPCell(new Phrase("Balance",table_header_font)));
                statement_table.addCell(new PdfPCell(new Phrase(reason,regularFont)));
                statement_table.addCell(new PdfPCell(new Phrase(String.valueOf(balance),regularFont)));
            } else if(reason.equals("Other Reason")){
                statement_table.addCell(new PdfPCell(new Phrase("Reason",table_header_font)));
                statement_table.addCell(new PdfPCell(new Phrase(other_reason,regularFont)));

            }
            document.add(statement_table);

            document.add(new Paragraph(" "));

            document.add(new Paragraph("HD Signature:..............."));

            document.add(new Paragraph(" "));

            addGeneratedNote(document);
            document.close();
    }

    public static void generateGradeLeaveReport(String grade,String stream,String term,String outputpath,List<Map<String,Object>> leave_data)throws Exception{
        Document document = new Document();

        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(outputpath));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","LEAVE REPORT","resources/images/logo.png");

        document.add(new Paragraph(" "));

        PdfPTable top = new PdfPTable(3);
        top.setWidths(new float[]{2,2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Grade",header_font)));
        top.addCell(new PdfPCell(new Phrase("Stream",header_font)));
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(grade,row_font)));
        top.addCell(new PdfPCell(new Phrase(stream,row_font)));
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable leave_table = new PdfPTable(8);
        leave_table.setWidthPercentage(100);
        leave_table.setWidths(new float[]{2,3,2,2,2,2,2,2});
        String[] headers = {"Reg No","Name","Reason","Other Reason","Date of Leave","Time","Return Date","Term"};
        for(String header : headers){
            leave_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : leave_data){
            System.out.println("Data from pdf method: "+data.get("reg_no").toString()+data.get("name").toString());
            leave_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("reason").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("other_reason").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("date_of_leave").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("time").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("return_date").toString(),row_font)));
        }
        document.add(leave_table);
        addGeneratedNote(document);
        addFooter(writer);
        document.close();
    }

    public static void generateTermLeaveReport(String grade,String stream,String term,String year,String path,List<Map<String, Object>> leave_data) throws Exception{
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(path));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","LEAVE REPORT","resources/images/logo.png");
    
        PdfPTable top = new PdfPTable(2);
        top.setWidths(new float[]{2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));
        top.addCell(new PdfPCell(new Phrase("Year",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        top.addCell(new PdfPCell(new Phrase(year,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable leave_table = new PdfPTable(9);
        leave_table.setWidths(new float[]{2,3,2,2,2,2,2,2,2});
        leave_table.setWidthPercentage(100);
        String[] headers = {"Reg No","Name","Grade","Stream","Reason","Other Reason","Date of Leave","Time","Return Date"};

        for (String header : headers){
            leave_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : leave_data){
            leave_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("grade").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("stream").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("reason").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("other_reason").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("date_of_leave").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("time").toString(),row_font)));
            leave_table.addCell(new PdfPCell(new Phrase(data.get("return_date").toString(),row_font)));
        }
        document.add(leave_table);
        addFooter(writer);
        document.close();
    }

    public static void generateGradeFeeReport(String grade,String stream,String term,String outputpath,List<Map<String,Object>> fee_data)throws Exception{

        Document document = new Document();

        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(outputpath));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","FEE REPORT","resources/images/logo.png");
        
        document.add(new Paragraph(" "));

        PdfPTable top = new PdfPTable(3);
        top.setWidths(new float[]{2,2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Grade",header_font)));
        top.addCell(new PdfPCell(new Phrase("Stream",header_font)));
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(grade,row_font)));
        top.addCell(new PdfPCell(new Phrase(stream,row_font)));
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable fee_table = new PdfPTable(4);
        fee_table.setWidthPercentage(100);
        fee_table.setWidths(new float[]{2,2,2,2});
        String[] headers = {"Reg No","Name","Amount Paid","Balance"};
        for(String header : headers){
            fee_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : fee_data){
            fee_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("amount").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("balance").toString(),row_font)));
        }
        document.add(fee_table);
        addFooter(writer);
        document.close();
    }

    public static void generateTermFeeReport(String grade,String stream,String term,String year,String path,List<Map<String, Object>> fee_data) throws Exception{
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(path));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","FEE REPORT","resources/images/logo.png");
        
        PdfPTable top = new PdfPTable(2);
        top.setWidths(new float[]{2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));
        top.addCell(new PdfPCell(new Phrase("Year",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        top.addCell(new PdfPCell(new Phrase(year,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable fee_table = new PdfPTable(6);
        fee_table.setWidths(new float[]{2,3,2,2,2,2});
        fee_table.setWidthPercentage(100);
        String[] headers = {"Reg No","Name","Grade","Stream","Amount Paid","Balance"};

        for (String header : headers){
            fee_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : fee_data){
            fee_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("grade").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("stream").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("amount").toString(),row_font)));
            fee_table.addCell(new PdfPCell(new Phrase(data.get("balance").toString(),row_font)));
        }
        document.add(fee_table);
        addFooter(writer);
        document.close();
    }

    public static void generateGradeAttendanceReport(String grade,String stream,String term,String outputpath,List<Map<String,Object>> attendance_data)throws Exception{
        Document document = new Document();

        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(outputpath));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","ATTENDANCE REPORT","resources/images/logo.png");

        document.add(new Paragraph(" "));

        PdfPTable top = new PdfPTable(3);
        top.setWidths(new float[]{2,2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Grade",header_font)));
        top.addCell(new PdfPCell(new Phrase("Stream",header_font)));
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(grade,row_font)));
        top.addCell(new PdfPCell(new Phrase(stream,row_font)));
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable attendance_table = new PdfPTable(5);
        attendance_table.setWidthPercentage(100);
        attendance_table.setWidths(new float[]{2,3,2,2,2});
        String[] headers = {"Reg No","Name","Date of attendance","Time","Status"};
        for(String header : headers){
            attendance_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : attendance_data){
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("date_of_attendance").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("time").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("status").toString(),row_font)));
        }
        document.add(attendance_table);
        addGeneratedNote(document);
        addFooter(writer);
        document.close();
    }

    public static void generateTermAttendanceReport(String grade,String stream,String term,String year,String path,List<Map<String, Object>> attendance_data) throws Exception{
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(path));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","ATTENDANCE REPORT","resources/images/logo.png");
        
        PdfPTable top = new PdfPTable(2);
        top.setWidths(new float[]{2,2});
        top.setWidthPercentage(100);
        Font header_font = new Font(Font.HELVETICA,11,Font.BOLD);
        top.addCell(new PdfPCell(new Phrase("Term",header_font)));
        top.addCell(new PdfPCell(new Phrase("Year",header_font)));

        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        top.addCell(new PdfPCell(new Phrase(year,row_font)));
        document.add(top);

        document.add(new Paragraph(" "));

        PdfPTable attendance_table = new PdfPTable(7);
        attendance_table.setWidths(new float[]{2,3,2,2,2,2,2});
        attendance_table.setWidthPercentage(100);
        String[] headers = {"Reg No","Name","Grade","Stream","Date of attendance","Time","Status"};

        for (String header : headers){
            attendance_table.addCell(new PdfPCell(new Phrase(header,header_font)));
        }

        for(Map<String,Object> data : attendance_data){
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("grade").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("stream").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("date_of_attendance").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("time").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("status").toString(),row_font)));
        }
        document.add(attendance_table);
        addFooter(writer);
        document.close();
    }

    public static void generateTeachersAttendanceReport(String term,String year,List<Map<String,Object>> attendance_data,String path) throws Exception{
        Document document = new Document();
        PdfWriter writer = PdfWriter.getInstance(document,new FileOutputStream(path));
        document.open();
        addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","ATTENDANCE REPORT","resources/images/logo.png");
  
        

        PdfPTable top = new PdfPTable(2);
        top.setWidths(new float[]{2,2});
        top.setWidthPercentage(100);
        top.addCell(new PdfPCell(new Phrase("Term",table_header_font)));
        top.addCell(new PdfPCell(new Phrase("Year",table_header_font)));
        Font row_font = new Font(Font.HELVETICA,9);
        top.addCell(new PdfPCell(new Phrase(term,row_font)));
        top.addCell(new PdfPCell(new Phrase(year,row_font)));

        PdfPTable attendance_table = new PdfPTable(5);
        attendance_table.setWidths(new float[]{2,2,2,2,2});
        attendance_table.setWidthPercentage(100);
        String[] headers = {"Teacher No","Name","Date of Attendance","Time In","Status"};
        for(String header : headers){
            attendance_table.addCell(new PdfPCell(new Phrase(header,table_header_font)));
        }

        for (Map<String,Object> data : attendance_data){
            System.out.println(data.get("reg_no").toString());
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("reg_no").toString(),row_font)));
            System.out.println(data.get("name").toString());
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("name").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("date_of_attendance").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("time_in").toString(),row_font)));
            attendance_table.addCell(new PdfPCell(new Phrase(data.get("status").toString(),row_font)));
            System.out.println(data.get("status"));
        }
        document.add(attendance_table);
        document.add(new Paragraph(" "));
        addGeneratedNote(document);
        addFooter(writer);
        document.close();
    }


    public static void generateReportForm(String regno,String name,String grade,String stream,String term,String year,String[] subjects,Map<String,Object> average_exams,List<Map<String,Object>> opener_exams,List<Map<String,Object>> mid_exams,List<Map<String,Object>> end_exams,String total_marks,String mean_marks,String position,String ov_position, String outputPath) {
        Document document = new Document();
        try {

            Map<String,Object> openerMap = !opener_exams.isEmpty() ? opener_exams.get(0) : new HashMap<>();
            Map<String,Object> midMap = !mid_exams.isEmpty() ? mid_exams.get(0) : new HashMap<>();
            Map<String,Object> endMap = !end_exams.isEmpty() ? end_exams.get(0) : new HashMap<>();
        

            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            String f_name = average_exams.get("first_name").toString();
            
            writer.setPageEvent(new WatermarkPageEvent(f_name));
            document.open();
            addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","REPORT FORM","resources/images/logo.png");
            addFooter(writer);

            PdfPTable top = new PdfPTable(4);
            top.setWidths(new float[]{2,3,2,2});
            top.setWidthPercentage(100);
            String[] headers1 = {"Reg No","Name","Grade","Stream"};
            for(String header : headers1){
                top.addCell(new PdfPCell(new Phrase(header,table_header_font)));
            }
            
            String[] rows1 = {regno,name,grade,stream};
            for(String row : rows1){
                top.addCell(new PdfPCell(new Phrase(row,regularFont)));
            }
            document.add(top);
            document.add(new Paragraph(" "));

            PdfPTable top2 = new PdfPTable(2);
            top2.setWidths(new float[]{2,2});
            top2.setWidthPercentage(100);
            String[] headers2 = {"Term","Year"};
            for(String header : headers2){
                top2.addCell(new PdfPCell(new Phrase(header,table_header_font)));
            }
           
            String[] rows2 = {term,year};
            for(String row : rows2){
                top2.addCell(new PdfPCell(new Phrase(row,regularFont)));
            }
            document.add(top2);
            document.add(new Paragraph(" "));
            

            PdfPTable marks_table = new PdfPTable(5);
            marks_table.setWidths(new float[]{3,2,2,2,2});
            marks_table.setWidthPercentage(100);
            String[] results_headers = {"Subject","Opener","Mid Term","End Term","Averege"};
            for(String header : results_headers){
                marks_table.addCell(new PdfPCell(new Phrase(header,table_header_font)));
            }
            
            for(String subject : subjects){
                marks_table.addCell(new PdfPCell(new Phrase(subject,regularFont)));
                Object op = openerMap.getOrDefault(subject,"-");
                Object mid = midMap.getOrDefault(subject,"-");
                Object end = endMap.getOrDefault(subject,"-");
                // Object ave = averageMap.getOrDefault(subject,"-");

                marks_table.addCell(new PdfPCell(new Phrase(op.toString(),regularFont)));
                marks_table.addCell(new PdfPCell(new Phrase(mid.toString(),regularFont)));
                marks_table.addCell(new PdfPCell(new Phrase(end.toString(),regularFont)));
                marks_table.addCell(new PdfPCell(new Phrase(average_exams.get(subject).toString(),regularFont)));
            }

            document.add(marks_table);
            document.add(new Paragraph(" "));
            String[] ranks_headers = {"Total Marks","Mean Marks","Position","Overall Position"};
            PdfPTable ranks_table = new PdfPTable(4);
            ranks_table.setWidths(new float[]{2,2,2,2});
            ranks_table.setWidthPercentage(100);
            for(String header : ranks_headers){
                ranks_table.addCell(new PdfPCell(new Phrase(header,table_header_font)));
            }
            
            String[] ranks = {total_marks,mean_marks,position,ov_position};
            for(String rank : ranks){
                ranks_table.addCell(new PdfPCell(new Phrase(rank,regularFont)));
            }
            document.add(ranks_table);
            document.add(new Paragraph(" "));
            addGeneratedNote(document);
            document.close();
            System.out.println("Report form generated at: " + outputPath);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }


    public static void generateResultPaper(String studentName, String regNo, String summary, String outputPath) {
        Document document = new Document();
        try {
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(outputPath));
            document.open();
            addHeader(document,writer,"DANITECH PRIMARY SCHOOL","NYAHURURU","CLASS PERFOMANCE","resources/images/logo.png");
            addFooter(writer);

            document.add(new Paragraph("Results Summary", titleFont));
            document.add(new Paragraph("Student Name: " + studentName));
            document.add(new Paragraph("Reg No: " + regNo));
            document.add(new Paragraph("Date: " + LocalDate.now()));
            document.add(new Paragraph(" "));
            document.add(new Paragraph(summary, regularFont));

            addGeneratedNote(document);
            document.close();
            System.out.println("Result paper generated at: " + outputPath);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    static class WatermarkPageEvent extends PdfPageEventHelper {
        private final String watermarkText;

        public WatermarkPageEvent(String text) {
            this.watermarkText = text;
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            try {
                PdfContentByte canvas = writer.getDirectContentUnder();
                Font watermarkFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 52, Font.BOLD, new GrayColor(0.85f));
                Phrase watermark = new Phrase(watermarkText, watermarkFont);

                ColumnText.showTextAligned(canvas, Element.ALIGN_CENTER, watermark,
                        (document.right() - document.left()) / 2 + document.leftMargin(),
                        (document.top() + document.bottom()) / 2, 45);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    // private static class HeaderFooterHandler extends PdfPageEventHelper {
    //     private final String title;

    //     HeaderFooterHandler(String title){
    //         this.title = title;
    //     }
    //     @Override
    //     public void onEndPage (PdfWriter writer,Document document){
    //         PdfContentByte cb = writer.getDirectContent();

    //         try {
    //             Image logo = Image.getInstance(LOGO_PATH);
    //             logo.setAbsolutePosition(50,document.getPageSize().getHeight() - 80);
    //             logo.scaleToFit(50,50);
    //             logo.setTransparency(new int[]{0xF0,0XFF});
    //             cb.addImage(logo);

    //             ColumnText.showTextAligned(cb,Element.ALIGN_CENTER,new Phrase("ShuleBase -"+ title,titlefont),document.getPageSize().getWidth()/ 2,document.getPageSize().getHeight() - 40,0);


    //             ColumnText.showTextAligned(cb,Element.ALIGN_CENTER,new Phrase("Generated by shuleBase",textfont),(document.right() - document.left()) / 2 + document.leftMargin(),document.bottom()- 20, 0);
                
    //         } catch (Exception e){
    //             e.printStackTrace();
    //         }
    //     }
    // }
}

